### ISSUE TITLE
Add instructions for running the study from scratch

### ISSUE THREAD

**Issue by mikix** [smart-on-fhir/cumulus-library-covid#38]
Maybe in the readme or a separate markdown doc.

Instructions off the top of my head:
1. Export DocRefs from EHR
   - If working with a limited set of DocRefs, make sure that they are relevant for the Covid study and are dated between March 2020 and June 2022
3. Run the [covid-symptom ETL task](https://docs.smarthealthit.org/cumulus/etl/studies/covid-symptom.html)
4. Run covid_symptom library study
5. Export tables from the study in Athena with icd10 and ctakes labels into csv files (for chart-review later). I think these are correct:
   - `select encounter_ref, symptom_display from covid_symptom__symptom_ctakes_negation`
   - `select encounter_ref, symptom_display from covid_symptom__symptom_icd10`
6. Configure Label Studio like:
```
<View>
  <Labels name="label" toName="text">
    <Label value="Congestion or runny nose" background="#100"/>
    <Label value="Cough" background="#040"/>
    <Label value="Diarrhea" background="#008"/>
    <Label value="Dyspnea" background="#b00"/>
    <Label value="Fatigue" background="#0f0"/>
    <Label value="Fever or chills" background="#40a"/>
    <Label value="Headache" background="#afa"/>
    <Label value="Loss of taste or smell" background="#f0f"/>
    <Label value="Muscle or body aches" background="#9bf"/>
    <Label value="Nausea or vomiting" background="#0aa"/>
    <Label value="Sore throat" background="#a44"/>
  </Labels>
  <Text name="text" value="$text"/>
</View>
```
7. Identify notes to review
8. Run `cumulus-etl upload-notes --philter=disable --no-nlp` on those notes
9. Have humans review the charts
10. Export the annotations from Label Studio
11. Configure chart-review like:
```
labels:
  - Congestion or runny nose
  - Cough
  - Diarrhea
  - Dyspnea
  - Fatigue
  - Fever or chills
  - Headache
  - Loss of taste or smell
  - Muscle or body aches
  - Nausea or vomiting
  - Sore throat

annotators:
  human1: 1
  human2: 2
  icd10:
    filename: icd10.csv
  ctakes:
    filename: ctakes.csv
```
12. Run `chart-review accuracy`
